### ISSUE TITLE
Candlestick Charts

### ISSUE THREAD

**Issue by dhruvio** [terezka/elm-charts#109]
Thanks for making this library @terezka. A common chart in the finance world is the candlestick chart. Are there any plans to support candlestick charts on the roadmap?

Companies using candlestick charts in the wild:

- https://www.tradingview.com/chart/
- https://cryptowat.ch/charts/KRAKEN:BTC-USD

![Screen Shot 2022-01-26 at 11 48 40 AM](https://user-images.githubusercontent.com/2994670/151236054-b02120aa-cdf9-481e-9e5b-45df16011bce.png)

**Comment by NduatiK** [comment]
This should be possible (see this [Tweet](https://twitter.com/logachev_dev/status/1444128060459061248?cxt=HHwWgMCw3bq0yYooAAAA)). My guess is that you have to the custom chart element (shown [here](https://elm-charts.org/documentation/navigation/custom-chart-elements) and documented [here](https://package.elm-lang.org/packages/terezka/elm-charts/latest/Chart#custom)). 

You would just draw a rectangle for each of the candlesticks at the x matching the time value and a y1 and y2 that correspond to the min and max value of the stick.

**Comment by NduatiK** [comment]
This [gist](https://gist.github.com/NduatiK/b873b928693858727d4aaca293c2608e) should get you 95% of the way there.

![Screenshot 2022-04-03 181320](https://user-images.githubusercontent.com/28830783/161437430-53324ad4-d5a3-4200-a2b8-309031e77766.png)

**Comment by NduatiK** [comment]
Updated [here](https://gist.github.com/NduatiK/b873b928693858727d4aaca293c2608e) to include bottom bars on the candle sticks.

![image](https://user-images.githubusercontent.com/28830783/161448466-8e9cc1f9-0e97-4c4c-bccb-76a56c280351.png)

**Comment by dhruvio** [comment]
Amazing, thanks @NduatiK !
