### ISSUE TITLE
Why is there no junks in viewBarsCustom?

### ISSUE THREAD

**Issue by anagrius** [terezka/elm-charts#57]
Junks don't seem to be supported in `viewBarsCustom`. Any good reason for this?

**Comment by terezka** [comment]
Hi! You mean like they don't show up or you can't add them in the first place? It should use the same [customizations](http://package.elm-lang.org/packages/terezka/elm-plot/5.0.1/Plot#PlotCustomizations) as it does in viewSeriesCustom!

**Comment by anagrius** [comment]
Hi T,

Yes. But if you look at the view function for custom bars. It is not actually used in rendering. :)

**Comment by terezka** [comment]
... I see. That's a little silly and will be remedied in the next version! Until then, sorry for the inconvenience!
