### ISSUE TITLE
Need Help?

### ISSUE THREAD

**Issue by anagrius** [terezka/elm-charts#62]
We at Humio are really anxious to replace our Hacky Highcharts-in-Elm chart implementation.
We were going to build our own, but I think Elm-Plot is so promising that we would prefer to use it. (Good Work)

Only problem is that it seems to be in a big transition phase. Is it ready to start hacking on, or is it too unstable.

We would love to help out ( It is after all to our own benefit :) ), but we would need you to point us in the direction where we can be the most helpful.

**Comment by terezka** [comment]
Hi! So I'm current drowning in some conference work, but I'll be back to working on elm-plot after the 12th of June. There is a pretty much working version in the project-tear-apart branch - the only thing missing is the hint API which I'm working on as well as a better system for junk. Mostly it's a lot of design work, so there isn't much coding to do at the moment!

That said, is there anything, in particular, you'd like to work on?

**Comment by anagrius** [comment]
Time Charts and Interaction, are quite important for us. I guess that would be a start.
