### ISSUE TITLE
Status of elm-plot

### ISSUE THREAD

**Issue by sturgman** [terezka/elm-charts#80]
Hello,
I was wondering what is the plan for this library. I see that it says that it will be deprecated in the future, is it safe to use? Will the line package be similar enough to allow for an easy port? Why did you decide to separate the features in the library?

By the way thank you for making it available. I was about to dive into elm-visualization but then someone in elm slack suggested this and I was able to get something working (not perfect yet) very quickly.

**Comment by terezka** [comment]
Hi! The new libraries will be quiet similar, so a port shouldn't be too crazy. The reasoning was because the API gets better if I don't try to cramp all the chart types into one, but if they are not connected, there is no reason they should be in the same library.
