### ISSUE TITLE
Builds failing with HTTP 404

### ISSUE THREAD

**Issue by alienscience** [terezka/elm-charts#83]
We currently have a dependency to elm-plot
```
"terezka/elm-plot": "5.1.0 <= v <= 5.1.0"
```
However, builds started failing today with the following error:
```
14:19:45 Error: The following HTTP request failed.
14:19:45 <https://github.com/terezka/elm-plot/zipball/5.1.0/>
```

Has this project been renamed/removed? Is there a workaround?

Thanks in advance for any help.

Edit: As background information, we saw a similar error with a rename of the elm-transducers project:
  https://github.com/avh4-experimental/elm-transducers/issues/8

**Comment by benjaminparnell** [comment]
Also getting this issue, not sure what's happened

**Comment by allenap** [comment]
Hi @terezka, NRI builds are also breaking with the same error.

**Comment by avh4** [comment]
Yeah, looks like the same thing as with elm-transducers.  The "workaround" is to re-add the 5.1.0 tag to this repo until everyone upgrades to Elm 0.19.

**Comment by omnibs** [comment]
We forked, renamed and published the fork to get unblocked.

**Comment by terezka** [comment]
Oh, sorry you all! Fixing it now!

**Comment by alienscience** [comment]
In a similar way to https://github.com/avh4-experimental/elm-transducers/issues/8 we no longer get the HTTP  404 and the error has now changed to:
```
Error: Problem when downloading the terezka/elm-plot 5.1.0 code.
```
@omnibs Are you able to give the name of your fork? I looked in your repository listing and cannot find it.

**Comment by mariohuizar** [comment]
I could not found the @omnibs repo. So I republished version 5.1.0 under:
"mariohuizar/elm-plot": "1.0.0"
